# installation et configuration de webdav

- name: installing davfs2
  apt: pkg=davfs2 state=installed update_cache=yes

# création du répertoire /home/georchestra.user.xxxx/owncloud nécessaire au montage webdav
- name: create owncloud directory
  file: path=/home/{{ item.value.name }}/owncloud state=directory owner={{ item.value.name }} group=georchestra mode=0755
  with_dict: georchestra.user

# création du répertoire /home/georchestra.user.xxxx/.davfs2
- name: create .davfs2 directory
  file: path=/home/{{ item.value.name }}/.davfs2 state=directory owner={{ item.value.name }} group=georchestra mode=0755
  with_dict: georchestra.user

# le fichier .davfs2/secrets permet à georchestra.user.xxxx de réaliser le montage webdav vers owncloud
- name: template .davfs2/secrets for georchestra.user.xxxx user
  template: src=secrets.j2
            dest=/home/{{ item.value.name }}/.davfs2/secrets
            owner={{ item.value.name }} group=georchestra mode=0600  
  with_dict: georchestra.user

# modification de /etc/fstab pour le montage webdav
- name: modify /etc/fstab
  mount: name=/home/{{ item.value.name }}/owncloud
         src=https://{{ owncloud.fqdn }}/owncloud/remote.php/webdav
         fstype=davfs 
         opts=rw,user,noauto 
         state=present
  with_dict: georchestra.user

# davfs2 doit fonctionner sans verrou
- name: modify /etc/davfs2/davfs2.conf
  replace: dest=/etc/davfs2/davfs2.conf
           regexp='#\suse_locks\s+1'
           replace='use_locks 0'

# setuid bit sur mount.davfs pour permettre le montage en mode utilisateur
- name: setuid /usr/sbin/mount.davfs
  file: path=/usr/sbin/mount.davfs state=file mode="u=rws,g=rx,o=rx"

# georchestra.user.xxxx doivent être membre du group davfs2
- name: setting georchestra.user.xxxx in davfs2 group
  user: name={{ item.value.name }} groups=davfs2 append=yes
  with_dict: georchestra.user

