# creation du groupe georchestra
- name: test if georchestra group exists
  shell: cat /etc/group
  register: etc_group

- name: create georchestra group
  group: name=georchestra state=present gid=999
  when: "'georchestra' not in etc_group.stdout"

# creation de l'utilisateur georchestra
- name: create georchestra user
  user: name=georchestra comment=georchestra uid=999 group=georchestra shell=/bin/bash

# creation de l'utilisateur georchestra.open_user
- name: create georchestra.open_user user
  user: name={{ georchestra.open_user }} comment={{ georchestra.open_user }} uid=998 group=georchestra shell=/bin/bash

# le fichier .pgpass permet à georchestra.open_user de se connecter sur la base geoserver.db.name
- name: template pgpass for georchestra.open_user user
  template: src=pgpass.j2 
            dest=/home/{{ georchestra.open_user }}/.pgpass
            owner={{ georchestra.open_user }} group=georchestra mode=0600  

# /home/georchestra.open_user/.ssh contient les clés publique et privée
- name: create .ssh directory
  file: path=/home/{{ georchestra.open_user }}/.ssh state=directory owner={{ georchestra.open_user }} group=georchestra mode=0755

# copie des clés de l'utilisateur georchestra.open_user
- name: copy id_rsa.pub in .ssh directrory
  copy: src=/home/echiarello/certificats/georchestra-ouvert/id_rsa.pub 
        dest=/home/{{ georchestra.open_user }}/.ssh/id_rsa.pub 
        owner={{ georchestra.open_user }} group=georchestra mode=0644

- name: copy id_rsa in .ssh directrory
  copy: src=/home/echiarello/certificats/georchestra-ouvert/id_rsa
        dest=/home/{{ georchestra.open_user }}/.ssh/id_rsa
        owner={{ georchestra.open_user }} group=georchestra mode=0600

# configurer github pour georchestra.open_user
- name: template .gitconfig
  template: src=gitconfig.j2 dest=/home/{{ georchestra.open_user }}/.gitconfig

# script pour remplacer https par ssh pour les connexions vers github
# sera exécuté dans roles/geosync/tasks/main.yml
- name: template git_seturl.sh
  template: src=git_seturl.sh.j2 
            dest=/home/{{ georchestra.open_user }}/git_seturl.sh 
            owner={{ georchestra.open_user }} group=georchestra mode=0755

# creation de l'utilisateur georchestra.restrict_user
- name: create georchestra-restrict user
  user: name={{ georchestra.restrict_user }} comment=georchestra-restreint uid=997 group=georchestra shell=/bin/bash

# creation du répertoire /home/georchestra.open_user/owncloud
- name: create owncloud directory
  file: path=/home/{{ georchestra.open_user }}/owncloud 
        state=directory 
        owner={{ georchestra.open_user }} group=georchestra mode=0755

# creation du répertoire /home/georchestra.open_user/tmp
- name: create tmp directory
  file: path=/home/{{ georchestra.open_user }}/tmp state=directory owner={{ georchestra.open_user }} group=georchestra mode=0755

