# creation du répertoire de logs de geosync
- name: create geosync log directory
  file: path=/var/log/{{ item.value.logs }} state=directory owner={{ item.value.name }} group=georchestra mode=0755
  with_dict: georchestra.user

# installation de librairies pour traiter les fichiers xml
- name: installing libxml2-utils
  apt: pkg=libxml2-utils state=installed update_cache=yes

# clonage de geosync depuis github
- name: checkout geosync
  sudo: yes
  sudo_user: "{{ item.value.name }}"
  #git: repo=ssh://git@github.com/MaxiReglisse/geosync.git dest=/home/{{ georchestra.open_user }}/bin
  #git: repo=git://github.com/MaxiReglisse/geosync.git dest=/home/{{ georchestra.open_user }}/bin
  git: repo=https://github.com/MaxiReglisse/geosync.git dest=/home/{{ item.value.name }}/bin
       version={{ git.branch }}
  with_dict: georchestra.user

# modification du fd pour le flock, uniquement pour georchestra-restreint
# A AMELIORER
- name: modify fd for flock
  replace: dest=/home/{{ georchestra.user.rsct.name }}/bin/sync_data.sh
           regexp='200'
           replace='201'

# change git url : https -> ssh
- name: cd bin && ~/git_seturl.sh
  command: chdir=/home/{{ item.value.name }}/bin /home/{{ item.value.name }}/git_seturl.sh
  become: yes
  become_user: "{{ item.value.name }}"
  with_dict: georchestra.user

# fichier de configuration de geosync
- name: template geosync.conf
  template: src=geosync.conf.j2 dest=/home/{{ item.value.name }}/bin/.geosync.conf
  with_dict: georchestra.user

# mise en place d'un cron pour la synchronisation
- name: creates cronjob sync_data
  cron: minute="*/1" hour="08-20" weekday="1-5"
        name="geosync - importe les couches partagées via owncloud dans le geoserver"
        user="{{ item.value.name }}"
        job="/home/{{ item.value.name }}/bin/sync_data.sh >> /var/log/{{ item.value.logs }}/cron_error.log"
  with_dict: georchestra.user

