- name: geosync deployment
  hosts: my_georchestra_host
  sudo: yes
  roles:
    - geosync
  vars:
    owncloud: {
      fqdn: my_owncloud_server.my-organisation.org,
      user: owncloud_user,
      passwd: owncloud_password,
    }
    georchestra: {
      fqdn: my_georchestra_server.my-organisation.org,
      url: "https://my_georchestra_server.my-organisation.org",
      open_user: georchestra-ouvert,
      open_passwd: georchestra-ouvert_password,
      restrict_user: georchestra-restreint,
    }
    openldap: {
      basedn: "dc=georchestra,dc=my-organisation,dc=org",
      rootdn: "cn=admin,dc=my-organisation,dc=org",
      rootpw: secret,
    }
    openldap_adminemail: admin@my-organisation.org,
    geoserver: {
      workspace: geosync,
      datastore: shpowncloud, # Attention !!! ne pas finir le nom par "shp" sinon créer un datastore pour 1 seul shapefile
    }
    git: {
      branch: master,
      user : {
        name: my_github_user,
        email: my_github_user@my-organisation.org,
      }
    }
