# répertoire d'accueil des shapefiles
- name: create geoserver data directory
  file: path={{ geoserver.datadir }}/data state=directory owner=tomcat8 group=tomcat8 mode=0755

# création de l'espace de travail geosync
- name: create geoserver workspace
  command: >
    curl -v -u {{ georchestra.open_user }}:{{ georchestra.open_passwd }} -XPOST -H "Content-type: text/xml"
         -d "<workspace><name>{{ geoserver.workspace }}</name></workspace>"
            "{{ georchestra.url }}/geoserver/rest/workspaces"

# geosync est le workspace par défaut 
- name: define geoserver default workspace
  command: >
    curl -v -u {{ georchestra.open_user }}:{{ georchestra.open_passwd }} -XPUT -H "Content-type: text/xml" \
         -d "<workspace><name>{{ geoserver.workspace }}</name></workspace>" \
            "{{ georchestra.url }}/geoserver/rest/workspaces/default"
 
# création du datastore au sein du workspace shpowncloud
- name: create geoserver datastore
  file: path={{ geoserver.datadir }}/data/{{ geoserver.workspace }}/{{ geoserver.datastore }} 
        state=directory owner=tomcat8 group=tomcat8 mode=0755

# créer l'entrepôt (datastore) de shp : "owncloud" # attention : le datastore doit être en UTF-8
- name: create geoserver shp datastore
  command: >
    curl -v -u {{ georchestra.open_user }}:{{ georchestra.open_passwd }} -XPOST -H "Content-type: text/xml"
         -d "<dataStore><name>{{ geoserver.datastore }}</name>
                <description>shp dans owncloud</description>
                <type>Directory of spatial files (shapefiles)</type>
                <enabled>true</enabled>
                <connectionParameters>
                <entry key=\"charset\">UTF-8</entry>
                <entry key=\"url\">file:data/{{ geoserver.workspace }}/{{ geoserver.datastore }}</entry>
                <entry key=\"enable spatial index\">true</entry>
                <entry key=\"cache and reuse memory maps\">true</entry>
                </connectionParameters> 
             </dataStore>"
         "{{ georchestra.url }}/geoserver/rest/workspaces/{{ geoserver.workspace }}/datastores"

# créer l'entrepôt postgis de shp
- name: create geoserver postgis datastore
  command: >
    curl -v -u {{ georchestra.open_user }}:{{ georchestra.open_passwd }} -XPOST -H "Content-type: text/xml"
         -d "<dataStore>
               <name>{{ geoserver.pg_datastore }}</name>
               <connectionParameters>
                 <host>localhost</host>
                 <port>5432</port>
                 <database>{{ geoserver.db.name }}</database>
                 <user>{{ geoserver.db.user }}</user>
                 <passwd>{{ geoserver.db.pass }}</passwd>
                 <dbtype>postgis</dbtype>
               </connectionParameters>
             </dataStore>"
         https://{{ georchestra.fqdn }}/geoserver/rest/workspaces/geosync/datastores
